---
title: "data_manipulation"
Author: "Xue Zhang"
Date: "2023-09-19"
output: github_document
---



```{r}
library(tidyverse)

options(tibble.print_min = 5)
```


`pivot_longer`

load the PULSE biomarkers dataset from a .sas7bdat.

```{r}
pulse_df =
  haven::read_sas("./data/public_pulse_data.sas7bdat") |>
  janitor::clean_names()

pulse_df
```

fix problem using `pivot_longer`

```{r}
pulse_tidy_data =
  pivot_longer(
    pulse_df,
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi")

pulse_tidy_data
```

fix `visit`

```{r}
pulse_tidy_data = 
  pivot_longer(
    pulse_df,
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi")

pulse_tidy_data
```

use `mutate`



```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") |>
  janitor::clean_names() |>
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi") |>
  mutate(
    visit = replace(visit, visit == "bl", "00m"),
    visit = factor(visit))

print(pulse_df, n = 12)
```

`pivot_wider`

```{r}
analysis_result =
  tibble(
    group = c("treatment", "treatment", "placebo", "placebo"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 8, 3.5, 4)
  )

analysis_result
```

`pivot_wider`

```{r}
pivot_wider(
  analysis_result,
  names_from = "time",
  values_from = "mean")
```


`knitr::kable()`

```{r}
fellowship_ring =
  readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") |>
  mutate(movie = "fellowship_ring")

two_towers =
  readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") |>
  mutate(movie = "two_towers")

return_king =
  readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") |>
  mutate(movie = "return_king")
```

`bind_rows`

```{r}
lotr_tidy =
  bind_rows(fellowship_ring, two_towers, return_king) |>
  janitor::clean_names() |>
  pivot_longer(
    female:male,
    names_to = "gender",
    values_to = "words") |>
  mutate(race = str_to_lower(race)) |>
  select(movie, everything())

lotr_tidy
```


address a pet peeve

```{r}
pup_data =
  read_csv("./data/FAS_pups.csv") |>
  janitor::clean_names() |>
  mutate(
    sex =
      case_match(
        sex,
        1 ~ "male",
        2 ~ "female"),
    sex = as.factor(sex))

litter_data =
  read_csv("./data/FAS_litters.csv") |>
  janitor::clean_names() |>
  separate(group, into = c("dose", "day_of_tx"), sep = 3) |>
  relocate(litter_number) |>
  mutate(
    vt_gain = gd18_weight - gd0_weight,
    dose = str_to_lower(dose))

fas_data = 
  left_join(pup_data, litter_data, by = "litter_number")

fas_data
```







